from . import (
    # Core resources based on database tables
    admin_users,
    booking_requests,
    customers,
    customer_vouchers,
    facilities,
    facility_features,
    games,
    hotel_brands,
    promotions,
    rooms,
    room_amenities,
    room_features,
    room_stays,
    services,
    service_bookings,
    tenants,
    vouchers,
)

__all__ = [
    # Core resources
    "booking_requests",
    "customers",
    "customer_vouchers",
    "facilities",
    "facility_features",
    "games",
    "hotel_brands",
    "promotions",
    "rooms",
    "room_amenities",
    "room_features",
    "room_stays",
    "services",
    "tenants",
    "user",
    "vouchers",
]
